name: Bump version

on:
  push:


jobs:
  change_sth:
    runs-on: ubuntu-latest
    steps:
      - name: check
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Echo commit msg
        run: echo "${{ github.event.head_commit.message }}"
      - name: make file.txt
        run: grep -o '".*"' project.toml | sed 's/"//g' >> file.txt
      - name: update file.txt
        run: sed '2q;d' file.txt >> version.txt
      - name: commit file.txt
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Auto verssioning
          author_email: auto@version.com
          message: 'some commit'
          add: 'file.txt'
