name: BLLLLLLLLLLLL
on:
  pull_request_target:
    branches:
      - main
    types:
      - ready_for_review

jobs:
  change_sth:
    runs-on: ubuntu-latest
    steps:
      - name: check
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: sth
        run: echo "EEEE"
        
