name: Bump version
on:
  pull_request:
    branches:
      - main

jobs:
  change_sth:
    runs-on: ubuntu-latest
    steps:
      - name: check
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: sth
        run: echo "EEEE"
        
