name: Bump version

on:
  push:


jobs:
  change_sth:
    runs-on: ubuntu-latest
    steps:
      - name: check
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Echo commit msg
        run: echo "${{ github.event.head_commit.message }}"
      - name: make file.txt
        run: grep -o '".*"' project.toml | sed 's/"//g' >> file.txt
      - name: update file.txt
        run: sed '2q;d' file.txt >> version.txt
      - name: save to variable and echo
        id: version
        run: |
          old_version=`cat version.txt`
          echo $old_version
          echo "old_version=${old_version}" >> $GITHUB_ENV
      - name: other name
        run: echo "${{ env.old_version }}"
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: bump
        run: |
          python
          print("elo")
      - name: delete version.txt
        run: rm version.txt
      - name: commit file.txt
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Auto verssioning
          author_email: auto@version.com
          message: 'some commit'
          add: 'file.txt'
