name: Bump version

on:
  push:


jobs:
  change_sth:
    runs-on: ubuntu-latest
    steps:
      - name: check
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Echo commit msg
        run: echo "${{ github.event.head_commit.message }}"
      - name: make file.txt
        run: grep -o '".*"' project.toml | sed 's/"//g' >> file.txt
      - name: update file.txt
        run: sed '2q;d' file.txt >> version.txt
      - name: save to variable and echo
        run: |
          old_version=`cat version.txt`
          perl -i -pe 's/\d+\.\d+\.\K(\d+)/ $1+1 /e' version.txt
          new_version=`cat version.txt`
          cat version.txt
          echo "-----"
          echo $old_version
          echo $new_version
#          if [[ ${{ github.event.head_commit.message }} =~ "patch" ]];
#          then
#            perl -i -pe 's/\d+\.\d+\.\K(\d+)/ $1+1 /e' version.txt
#          elif [[ ${{ github.event.head_commit.message }} =~ "minor" ]];
#          then
#            perl -i -pe 's/\d+\.\d+\.\K(\d+)/ $1+1 /e' version.txt
#          elif [[ ${{ github.event.head_commit.message }} =~ "major" ]];
#          then
#            perl -i -pe 's/\d+\.\d+\.\K(\d+)/ $1+1 /e' version.txt
#          else
#            echo "No bump"
#          fi
#          newest_version=`cat version.txt`
#          echo "-----"
#          echo $old_version
#          echo $new_version
#          echo $newest_version
      - name: other name
        run: echo $new_version
      - name: delete version.txt
        run: rm version.txt
      - name: commit file.txt
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Auto verssioning
          author_email: auto@version.com
          message: 'some commit'
          add: 'file.txt'
