name: Bump version

on:
  push:


jobs:
  change_sth:
    runs-on: ubuntu-latest
    steps:
      - name: check
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Echo commit msg
        run: echo "${{ github.event.head_commit.message }}"
      - name: make file.txt
        run: grep -o '".*"' project.toml | sed 's/"//g' >> file.txt
      - name: update file.txt
        run: sed '2q;d' file.txt >> version.txt
      - name: save to variable and echo
        run: |
          version=`cat version.txt`
          echo $version
          echo "-----"
          echo $version
          TAG=$(
             echo "version" | while IFS=. read major minor patch; do
                 # add sanity-checks here
                 case "$1" in
                    patch)
                       echo "$major.$minor.$((patch+1))"
                       ;;
                    major)
                       echo "$((major+1).0.0"
                       ;;
                    minor|*)
                       echo "$major.$((minor+1)).0" 
                       ;;
                 esac
             done
          )
          echo $tag
      - name: delete version.txt
        run: rm version.txt
      - name: commit file.txt
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Auto verssioning
          author_email: auto@version.com
          message: 'some commit'
          add: 'file.txt'
