name: Bump version
on:
  pull_request_target:
    branches:
      - main
    types:
      - auto_merge_enabled

jobs:
  change_sth:
    runs-on: ubuntu-latest
    steps:
      - name: check
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: sth
        run: echo "EEEE"
        
