name: Bump version
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened

jobs:
  change_sth:
    runs-on: ubuntu-latest
    steps:
      - name: check
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: sth
        run: echo "EEEE"
