name: Bump version
on:
  push:
    branches:
      - main

jobs:
  add_tag:
    runs-on: ubuntu-lates
    steps:
    - id: build
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - id: new_tag
      uses: anothrNick/github-tag-action@1.40.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
  change_toml:
    runs-on: ubuntu-latest
    needs: add_tag
    steps:
    - run: echo ${{needs.add_tag.outputs.new_tag}}
