name: Bump version
on:
  push:
    branches:
      - main

jobs:
  add_tag:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{steps.new_tag.outputs.new_tag}}
      old_tag: ${{steps.old_tag.outputs.tag}}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - id: old_tag
      name: Get old tag
      uses: oprypin/find-latest-tag@v1
      with:
        repository: tomaszwarda/version
    - id: new_tag
      name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.40.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
  no_v:
    runs-on: ubuntu-latest
    needs: add_tag
    outputs:
      new_tag_no_v: ${{steps.no_v_old.outputs.test}}
      old_tag_no_v: ${{steps.no_v_new.outputs.test}}
    steps:
      - id: no_v_old 
        run: |
          echo "${{needs.add_tag.outputs.old_tag}}" > $OLD_TAG
          echo "${OLG_TAG//v/}"
      - id: no_v_new
        run: |
          echo "${{needs.add_tag.outputs.new_tag}}" > $NEW_TAG
          echo "${NEW_TAG//v/}"
  change_toml:
    runs-on: ubuntu-latest
    needs: no_v
    steps:
    - run: |
        echo ${{needs.no_v.outputs.new_tag_no_v}}
        echo ${{needs.no_v.outputs.old_tag_no_v}}
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "${{needs.no_v.outputs.old_tag_no_v}}"
        replace: "${{needs.no_v.outputs.new_tag_no_v}}"
        include: "project.toml"

