name: Bump version
on:
  push:
    branches:
      - main

jobs:
  add_tag:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{steps.new_tag.outputs.new_tag}}
      old_tag: ${{steps.old_tag.outputs.tag}}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - id: old_tag
      name: Get old tag
      uses: oprypin/find-latest-tag@v1
      with:
        repository: tomaszwarda/version
    - id: new_tag
      name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.40.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
  change_toml:
    runs-on: ubuntu-latest
    needs: add_tag
    steps:
    - run: echo ${{needs.add_tag.outputs.new_tag}}
    - run: echo ${{needs.add_tag.outputs.old_tag}}
    - run: |
        OLD_TAG="${OLD_TAG//v/}"
        NEW_TAG="${NEW_TAG//v/}"
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "${OLD_TAG}"
        replace: "${NEW_TAG}"
        include: "project.toml"
    - run: |
        echo ${OLD_TAG}
