name: Bump version
on:
  push:
    branches:
      - main

jobs:
  add_tag:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{steps.tag.outputs.new_tag}}
      old_tag: ${{steps.old.outputs.tag}}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - uses: little-core-labs/get-git-tag@v3.0.1
      id: old
      with:
        tagRegex: "foobar-(.*)"  # Optional. Returns specified group text as tag name. Full tag string is returned if regex is not defined.
        tagRegexGroup: 1 # Optional. Default is 1.
#     - name: Some other step # Output usage example
#       with:
#         tagname: ${{ steps.tagName.outputs.tag }}
    - id: tag
      name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.40.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
  change_toml:
    runs-on: ubuntu-latest
    needs: add_tag
    steps:
    - run: echo ${{needs.add_tag.outputs.new_tag}}
    - run: echo ${{needs.add_tag.outputs.old_tag}}
